apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "activemq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: openwire
      port: {{ .Values.service.amqpPort }}
      targetPort: openwire
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
